// Generated by CoffeeScript 1.3.1
(function() {
'use strict';
  var cfg, mods;

  __testacular__.loaded = function() {};

  cfg = {
    modules: {
      angular: {
        path: '/static/lib/angular-1.1.1/angular.js',
        async: false
      },
      'angular-resource': {
        path: '/static/lib/angular-1.1.1/angular-resource.js',
        async: false,
        requires: ['angular']
      },
      'angular-mocks': {
        path: '/static/lib/angular-1.1.1/angular-mocks.js',
        async: false,
        requires: ['angular']
      },
      chai: {
        path: '/test/lib/chai/chai.js',
        async: false
      },
      config: {
        path: '/static/js/cfg.js',
        requires: ['angular']
      },
      controllers: {
        path: '/static/js/controllers/index.js',
        requires: ['angular', 'angular-resource']
      },
      'filters': {
        path: '/static/js/filters/index.js',
        requires: ['angular']
      },
      services: {
        path: '/static/js/services/index.js',
        requires: ['angular', 'angular-resource']
      },
      app: {
        path: '/static/js/app.js',
        requires: ['angular', 'angular-resource', 'config', 'controllers', 'services']
      }
    },
    base: '/base'
  };

  mods = ['chai'];

  YUI(cfg).use(mods, function(Y) {
    window.expect = chai.expect;
    window.should = chai.should();
    return window.__testacular__.start();
  });

}).call(this);
